### ISSUE TITLE
New doesn't seem to work

### ISSUE THREAD

**Issue by bronson** [withastro/astro.new#28]
Any time I try to generate a new project, I get:

![image](https://user-images.githubusercontent.com/1776/227373195-f1571ba2-744f-48c4-a631-da4c77b0b43c.png)

That error was created by clicking on one of the links in the README: [astro.new/docs?on=stackblitz](https://astro.new/docs?on=stackblitz)

But everything seems to be failing. Every link in the README, plus going to https://astro.new/ or https://astro.new/next/ and clicking on any of the "Open In" buttons produces then same error.

Browsers are Chromium Version 111.0.5563.64 or Firefox 110.0.

**Comment by delucis** [comment]
Thank you for the report @bronson! @itsMapleLeaf fixed this in #29 so hopefully you should see this working now — let me know if you don’t!

**Comment by bronson** [comment]
yep fixed :+1:
