### ISSUE TITLE
NOT URGENT: update links to example templates to generate from withastro/astro instead of snowpackjs/astro

### ISSUE THREAD

**Issue by sarah11918** [withastro/astro.new#5]
Just a heads up that I imagine this will be wanted at some point? (Redirects are working fine, so no worries at the moment!) 

Also, I can't actually verify that all the new links are working, because I think I'm opening too many at once and confusing the platforms.  :P

I don't know whether just updating snowpackjs to withastro in the utils/index.ts is the only change needed, and I can't test updating the actual site links myself because of the api authorization header token needed.

![Screenshot 2021-11-24 10 15 05](https://user-images.githubusercontent.com/5098874/143256723-b5d9804f-9f70-42a6-9db9-fbdc039b4e2a.png)

So, I know this isn't exactly helpful at this moment, but it's just a reminder to have on the radar for the future!

**Comment by natemoo-re** [comment]
Just pushed some updates to fix this! Thanks for opening an issue ☺️
