### ISSUE TITLE
IDEA: Adding Gitpod buttons eventually?

### ISSUE THREAD

**Issue by sarah11918** [withastro/astro.new#6]
A Gitpod community member has contributed https://github.com/withastro/astro/pull/2789 to /astro which now makes it possible to open an individual starter template in Gitpod, with pre-build instructions for installing our VS code extension, prettier, lint etc.  🥳 

Just putting it out there that if that pans out, we can be adding buttons (more buttons!) to this page for our individual starters that lead directly into Gitpod.

**Comment by aFuzzyBear** [comment]
Lets make this happen,
