### ISSUE TITLE
Add `create astro --template` commands to dropdown

### ISSUE THREAD

**Issue by lorenzolewis** [withastro/astro.new#70]
It would be a nice QOL enhancement to have a mechanism for users to directly copy a `create astro` command for a given template as outlined in https://docs.astro.build/en/install-and-setup/

**Comment by Fryuni** [comment]
Example of how it could be:
![image](https://github.com/user-attachments/assets/4059dbce-1298-4759-beea-4957ab763472)


Haven't added style at all, just to have an example of what this is about
