### ISSUE TITLE
BUG: fast-build and portfolio-svelte throw an error

### ISSUE THREAD

**Issue by shaal** [withastro/astro.new#8]
Steps to replicate:
Go to https://astro.new/
![image](https://user-images.githubusercontent.com/22901/158635979-69f32602-1682-435f-9053-6249856db685.png)

If you click on any button in `fast-build` or `portfolio-svelte` panels, you'll get an error message -
```
Unable to find fast-build! Supported templates are:
  - blog-multiple-authors
  - blog
  - component
  - docs
  - env-vars
  - framework-alpine
  - framework-lit
  - framework-multiple
  - framework-preact
  - framework-react
  - framework-solid
  - framework-svelte
  - framework-vue
  - minimal
  - non-html-pages
  - portfolio
  - ssr
  - starter
  - subpath
  - with-markdown-plugins
  - with-markdown-shiki
  - with-markdown
  - with-nanostores
  - with-tailwindcss
  - with-vite-plugin-pwa
```

**Comment by natemoo-re** [comment]
Thanks! This list is out of date since we haven't deployed the site in a while. This should be fixed shortly.
