### ISSUE TITLE
BUG: accessibility issues

### ISSUE THREAD

**Issue by shaal** [withastro/astro.new#9]
* Not enough color contrast between text and background for Gitpod buttons
* No alt text for images
![image](https://user-images.githubusercontent.com/22901/158713950-8a1a9c02-4e8a-47ef-917b-bc5d6e4be6f7.png)

I think a nice solution would be changing the markup from
```html
<a href="/minimal?on=stackblitz" aria-label="Open in StackBlitz" class="astro-WTK4WGHX">
  <img height="32" src="/open-in-stackblitz.svg" aria-hidden="true" class="astro-WTK4WGHX">
</a>
```

to
```html
<a href="/minimal?on=stackblitz" class="astro-WTK4WGHX">
  <img height="32" src="/open-in-stackblitz.svg" alt="" class="astro-WTK4WGHX">
  Open in StackBlitz
</a>
```

* The <img> should be svg of just the logo.
* The style of <a> would have the service's background color.

It's better using semantic HTML without Aria whenever possible.

**Comment by sarah11918** [comment]
I think we can close this one now since the site has been redesigned, and these aren't images requiring alt text anymore?  :sweat_smile: 

Shaal, do feel free to take a look at the new site though and let us know if you notice any accessibility issues! :purple_heart:
